name: Release & Docker Build

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      is_prerelease:
        description: 'Is this a pre-release?'
        type: boolean
        required: true
        default: false
      release_tag:
        description: 'The tag name for the release (e.g., v1.0.0)'
        type: string
        required: true
      target_commitish:
        description: 'The commitish value that determines where the Git tag is created from. Can be any branch, commit, or tag.'
        type: string
        required: false

jobs:
  # 设置全局变量
  set-globals:
    runs-on: ubuntu-latest
    outputs:
      is_prerelease: ${{ github.event_name == 'release' && github.event.release.prerelease || github.event_name == 'workflow_dispatch' && github.event.inputs.is_prerelease }}
      release_tag: ${{ github.event_name == 'release' && github.ref_name || github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag }}
      target_commitish: ${{ github.event_name == 'release' && github.event.release.target_commitish || github.event_name == 'workflow_dispatch' && (github.event.inputs.target_commitish || github.ref) }}
      ref_name: ${{ github.event_name == 'release' && github.ref_name || github.event_name == 'workflow_dispatch' && github.event.inputs.release_tag }}
      event_name: ${{ github.event_name }}
    steps:
      - name: Dummy Step to set outputs
        run: echo "Setting global variables..."

  # 调用测试工作流
  call-test:
    uses: ./.github/workflows/test.yml
    with:
      base_sha: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}
      head_sha: ${{ github.sha }}
    secrets: inherit

  # 交叉编译
  build:
    needs: [set-globals, call-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin]
        arch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Build Binary for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          BIN_DIR=./bin
          mkdir -p $BIN_DIR
          OUTPUT_NAME="curetmdbanime-${{ matrix.os }}-${{ matrix.arch }}"
          VERSION="${{ needs.set-globals.outputs.release_tag }}"

          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_ENABLED=0 go build \
            -ldflags "-X curetmdbanime/internal/config.Version=${VERSION}" \
            -o "${BIN_DIR}/${OUTPUT_NAME}" .

      - name: Upload Binaries
        uses: actions/upload-artifact@v6
        with:
          name: binaries-${{ matrix.os }}-${{ matrix.arch }}
          path: ./bin

  # Docker 构建
  docker_build:
    needs: [set-globals, call-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/curetmdbanime
          tags: |
            type=raw,value=latest,enable=${{ !needs.set-globals.outputs.is_prerelease && needs.set-globals.outputs.event_name == 'release' }}
            type=raw,value=preview,enable=${{ needs.set-globals.outputs.is_prerelease }}
            type=raw,value=${{ needs.set-globals.outputs.ref_name }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ needs.set-globals.outputs.release_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 发布任务，在 GitHub Release 发布时上传
  release:
    needs: [set-globals, build]
    runs-on: ubuntu-latest
    if: needs.set-globals.outputs.event_name == 'release' || needs.set-globals.outputs.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          ref: ${{ needs.set-globals.outputs.target_commitish }}

      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts
          pattern: binaries-*

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*
          tag_name: ${{ needs.set-globals.outputs.release_tag }}
          name: ${{ needs.set-globals.outputs.release_tag }}
